//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnglishLearning.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public string Mean { get; set; }
        public string Type { get; set; }
        public string IPA { get; set; }
        public string Example { get; set; }
        public Nullable<int> Level { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> Theme_ID { get; set; }
    
        public virtual Theme Theme { get; set; }
    }
}
